### ISSUE TITLE
donation

### ISSUE THREAD

**Issue by beaverweaver** [FuzzyBearBTC/android-peercoinwallet#31]
I'd like to make a large donation on for your projects, but I don't like the tip4commit scheme, , can you contact me on beaverweaver1122@mail.ru, and discus your plans about projects, I want you to guide the development with that funds, so we get better result in a lesser time

**Comment by FuzzyBearBTC** [comment]
@beaverweaver email sent

**Comment by FuzzyBearBTC** [comment]
Not had an email reply from you @beaverweaver but the Peer4commit has seen 9000 PPC donated in the last day, did you decide to go that route? or feel free to email me if you did reply and I missed it!! 

Regards
Fuzzybear

**Comment by beaverweaver** [comment]
yes that was me, think it would help the project

**Comment by FuzzyBearBTC** [comment]
@beaverweaver really appreciated and I hope to make you proud :) over next few weeks mycilium developers should be outlinine the scope of adding altcoins to the android bitcoin wallet they run, from here we will have a clear set of goals and development path to head down so do keep an eye on this repo and the forum peercointalk.org where I will no doubt be announcing any important updates etc.

Thanks again, its donations like this that really help drive the much needed constant development.

Fuzzybear
